# Generated by Django 5.2.5 on 2025-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('work', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('ytlink', models.TextField(blank=True, null=True)),
                ('myimg', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('aboutimg1', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('aboutimg2', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icons', models.ImageField(blank=True, null=True, upload_to='skill')),
                ('skillicon', models.ImageField(blank=True, null=True, upload_to='skill')),
            ],
        ),
    ]
